### ISSUE TITLE
Home Position Switch not working

### ISSUE THREAD

**Issue by hcomet** [brownrb/myFP2EFirmware#17]
The home position switch code looks to have been rewritten since release 122. The new code relies on HPS_alert which is defined in generalDefinitions.h using:

#ifdef HOMEPOSITIONSWITCH
#define HPS_alert             !((bool)digitalRead(HPSWPIN))
#else
#define HPS_alert             false
#endif

Unfortunately HOMEPOSITIONSWITCH is defined in focuserconfig.h which is included in myFP2ESP.ino after the include for generalDefinitions.h. This results in HOMEPOSITIONSWITCH never being defined when checked by the ifdef in generalDefinitions.h so the value of HPS_alert is always false disabling the homing switch.

I also tried the new homing switch test: HOMEPOSITIONSWITCH2 but it suffers from the same issue, HOMEPOSITIONSWITCH is never defined so HPS_alert is never properly defined in generalDefinitions.h.

**Comment by hcomet** [comment]
I should have mentioned that I found this issue with the release 135 that was on sourceforge but it looks like the latest master on github has the same code structure and issue, Couldn't confirm because I can't compile (see other issue). 

BTW: since the Windows app has a check homing switch state function I was surprised that it does work.  Looks life the response to that query skips the use of HPS_alert and returns the actual pin state.

**Comment by brownrb** [comment]
I see and understand the problem
The code in generalDefinitions.h
#ifdef HOMEPOSITIONSWITCH
#define HPS_alert             !((bool)digitalRead(HPSWPIN))
#else
#define HPS_alert             false
#endif
cannot possibly work because HOMEPOSITION has not been defined. HOMEPOSITION is only defined in focuserconfig.h which is not referenced by generalDefinitions.h and focuserconfig.h is only included later on in the compile stage.

HPS_alert is a macro and thus not easily changed. HPS_alert is used in myBoards.cpp and the main ino file.
It is difficult to place this into myBoards.h because that is not exposed to focuserconfig.h either.

it cannot be placed into focuserconfig.h because generalDefinitions.h/.cpp and myboards.h/.cpp do not reference focuserconfig.h either

I am working on it

**Comment by brownrb** [comment]
I have applied the fix directly into master branch. HPSW should now work.
Version number 135
